spring:
  cloud:
    gateway:
      routes:
        - id: after_route
          uri: http://httpbin.org:80/get
          filters:
#            - AddRequestHeader=hello, world
#            - RequestTime=true
          predicates:
            - After=2020-02-12T11:05:00.324+08:00[Asia/Shanghai]

        - id: query_route
          uri: http://httpbin.org:80/get
          predicates:
            - Query=foo