server:
  port: 8763
  tomcat:
    max-threads: 800
    uri-encoding: UTF-8
    basedir: /data/tmp
  servlet:
    context-path: /

spring:
  profiles:
    active: dev
  cloud:
    loadbalancer:
      retry:
        enabled: true